export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = " SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = " SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = " SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_HOTEL_BEGIN = "GET_HOTEL_BEGIN";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";

export const DELETE_HOTEL_BEGIN = "DELETE_HOTEL_BEGIN";
export const DELETE_HOTEL_ERROR = "DELETE_HOTEL_ERROR";
